---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Python3 and pip
  apt:
    name:
      - python3
      - python3-pip
    state: present

- name: Install Uvicorn and FastAPI
  pip:
    name:
      - uvicorn
      - fastapi
    executable: pip3

- name: Create application directory
  file:
    path: /opt/uvicorn_app
    state: directory
    owner: ubuntu
    mode: '0755'

- name: Copy application files
  copy:
    src: /path/to/your/app
    dest: /opt/uvicorn_app
    owner: ubuntu
    mode: '0755'

- name: Set up Uvicorn systemd service
  template:
    src: uvicorn.service.j2
    dest: /etc/systemd/system/uvicorn.service

- name: Start and enable Uvicorn service
  systemd:
    name: uvicorn
    enabled: yes
    state: started
